include: package:lints/recommended.yaml

analyzer:
  plugins:
    - dart_code_linter
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
# Error Rules
    - avoid_slow_async_io
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements

# Style Rules
    - always_declare_return_types
    - always_put_control_body_on_new_line # works against dartfmt
    - always_put_required_named_parameters_first
    - always_specify_types # More disbuting
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_returning_this
    - avoid_setters_without_getters
    # - avoid_types_on_closure_parameters # confilict always_specify_types
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - directives_ordering
    - join_return_with_assignment
    - library_prefixes
    # - lines_longer_than_80_chars
    # - omit_local_variable_types # conflict always_specify_types
    - one_member_abstracts
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_locals
    - prefer_foreach
    - prefer_single_quotes
    - public_member_api_docs
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable

dart_code_linter:
  extends:
    - package:dart_code_linter/presets/recommended.yaml
    - package:dart_code_linter/presets/metrics_recommended.yaml

  rules:
  - prefer-correct-identifier-length:
      exceptions: [ 'ok' ]
      exclude:
        - test/**
  - format-comment: false
  - no-magic-number: false
