name: http_status
description: Http Status Codes for dart.
version: 1.0.0+3
homepage: https://bitbucket.org/era_productions/http_status
author: Andrea Cantafio <kk4r.1m@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  coverage: ^0.9.2

dev_dependencies:
  test: ^0.12.0
