name: http_status
description: Http Status Codes for dart.
version: 1.0.0+1
homepage: https://bitbucket.org/era_productions/http_status
author: Andrea Cantafio <kk4r.1m@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  coverage: ^0.7.0
  dart_codecov_generator: ^0.4.0

dev_dependencies:
  test: ^0.12.0
